FROM openjdk:24-jdk AS build
COPY . .
RUN mvm clean package -DskipTests

FROM openjdk:24-slim
COPY --from=build /target/myFirsWebProject-3.3.5.jar myFirsWebProject.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","myFirsWebProject.jar" ]